mysql:
  image: mysql
  restart: always
  volumes:
   - ./db-init:/docker-entrypoint-initdb.d
  environment:
   - MYSQL_DATABASE=mydb
   - MYSQL_ROOT_PASSWORD=1234qwer
   - MYSQL_USER=dbuser
   - MYSQL_PASSWORD=dbpassword
  ports:
      - "3306:3306"
